[package]
name = "ronaldos-webserver"
version = "1.1.0"
edition = "2021"
authors = ["Sven Rademakers <sven.rademakers@gmail.com>"]
description = "Rust https server including ronaldo's own specific http services"

[dependencies]
clap = { version="*", features = ["derive"] }
ronaldos_config = { path="../ronaldos_config" }
tokio = { version = "*", features = ["net", "fs", "rt", "rt-multi-thread", "macros", "io-util", "sync"] }
tokio-stream = { version = "*", features = ["fs"] }
bytes = "*"
async-trait = "*"
http = "*"
log = "*"
hyper = {version = "*", features = ["full", "tcp"]}
futures-util = "*"
serde_json= "*"
serde = { version = "*", features = ["derive"] }
syslog = "*"
once_cell = "*"
base64="*"
serde_yaml="*"
hyper_rusttls = { path= "../hyper_rusttls" }
chrono = { version = "*", features = ["serde"] }
regex = "*"
notify = "*"
uuid = { version= "*", features = ["v4", "serde"] }
anyhow = "*"

[target.'cfg(not(windows))'.dependencies]
daemonize = "*"

[dev-dependencies]
tempdir = "*"