name: aarch64-openwrt-merlin
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always

jobs:
  aarch64-build:
    runs-on: ubuntu-latest
    env:
      RUST_TARGET: "aarch64-unknown-linux-gnu"
    steps:
      - name: checkout git repo
        uses: actions/checkout@v2
      - name: build http-server
        run: |
          chmod -R 777 $GITHUB_WORKSPACE &&\
          docker run -dt -v $GITHUB_WORKSPACE:$GITHUB_WORKSPACE --name asuswrt-merlin-build acrisliu/asuswrt-merlin-build &&\
          docker exec --workdir $GITHUB_WORKSPACE \
          -e RUST_TARGET=$RUST_TARGET \
          -e PASSWORD=${{ secrets.PASSWORD }} \
          -e USERNAME=${{ secrets.USERNAME }} \
          asuswrt-merlin-build scripts/build_aarch64_openwrt.sh
      - name: archiving .ipk package and create index
        run: |
          cargo install cargo-get &&\
          git clone --depth 1 https://git.yoctoproject.org/opkg-utils &&\
          cd ./opkg-utils && sudo make install && cd .. &&\
          RUST_OUT=http_server/target/$RUST_TARGET/release \
          IPK_DIR=ronaldos_package \
          REPOSITORY_DIR=ronaldos_repository \
          GROUP=root \
          OWNER=admin \
          scripts/create_ipk.sh
      # - name: upload artifacts
      #   if: always()
      #   uses: actions/upload-artifact@v3.0.0
      #   with:
      #     name: ronaldos_repository
      #     path: |
      #       http_server/target/*/release/build/*/output
      #       http_server/target/*/build/*/output
      - name: updating package index
        uses: siva1024/scp-deployer@v1.0
        with:
          host: svenrademakers.com 
          username: admin
          key: ${{ secrets.SSH_PASS }}
          source: ronaldos_repository
          target: /opt/share/nginx/html
