name: Jelena website CI
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always

jobs:
  debian-build:
    runs-on: ubuntu-latest
    env:
      API_KEY: ${{ secrets.API_KEY }}
      USERNAME: ${{ secrets.USERNAME }}
      PASSWORD: ${{ secrets.PASSWORD }}
    steps:
      - name: install aarch64 target for cargo
        run: sudo apt-get install gcc-aarch64-linux-gnu && rustup target add aarch64-unknown-linux-gnu && cargo install cargo-deb
      - name: checkout git repo
        uses: actions/checkout@v2
      - name: build aarch64 target
        run: cargo build --manifest-path http_server/Cargo.toml --release --target aarch64-unknown-linux-gnu
      - name: packaging .deb archive
        run: cargo deb --no-build --manifest-path http_server/Cargo.toml
      - name: Archive deb package
        uses: actions/upload-artifact@v2
        with:
          name: flaunch deb package
          path: target/debian/*.deb
