name: create packages
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  archive_files:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Create ronaldo-sys packages
        run: ./scripts/gen_ronaldo_packages.sh

      - name: Upload the archive
        uses: actions/upload-artifact@v3
        with:
          name: ronaldo-sys-archive
          path: ronaldo-sys*

