name: aarch64-openwrt-merlin
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always

jobs:
  aarch64-build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout git repo
        uses: actions/checkout@v2
      - name: build http-server
        run: |
          docker run -dt -v $GITHUB_WORKSPACE:$GITHUB_WORKSPACE --name nix-container nixos/nix &&\
          docker exec --workdir $GITHUB_WORKSPACE \
          -e PASSWORD=${{ secrets.PASSWORD }} \
          -e USERNAME=${{ secrets.USERNAME }} \
          nix-container nix --extra-experimental-features 'nix-command flakes' build .
      - name: updating package index
        uses: appleboy/scp-action@master
        with:
          host: "svenrademakers.com"
          username: "admin"
          key: ${{ secrets.SSH_PASS }}
          source: "result"
          target: "/opt/share/nginx/html"
